Add guide for running the txn processor locally
IntelLedger/omi-summer-lab pull request #23
Opened 2017-06-07 22:35 UTC by peterschwarz

Signed-off-by: Peter Schwarz <pschwarz@bitwise.io>

2017-06-07 22:38 UTC, jsmitchell requested changes

2017-06-07 22:38 UTC, jsmitchell commented on docs/source/txn_processor_dev.rst
> +  $ docker-compose -f omi-summer-lab/docker/compose-with-omi.yaml down
without

2017-06-07 22:38 UTC, jsmitchell commented on docs/source/txn_processor_dev.rst
> +validating the transaction payload and setting  global state values happen.
s/setting  global/setting global/

2017-06-08 01:22 UTC, nick-drozd requested changes

2017-06-08 01:22 UTC, nick-drozd commented on docs/source/txn_processor_dev.rst
> +We can now run the Transaction Processor. In the `omi-summer-lab` direcotry,
directory

2017-06-08 01:22 UTC, nick-drozd commented on docs/source/txn_processor_dev.rst
> +You could, for example, build sample payment record transaction for a number of
build a sample

2017-06-08 01:22 UTC, nick-drozd commented on docs/source/txn_processor_dev.rst
> +signed by the streaming service identity (i.e. “youtube” or “spotify”). The
e.g.

2017-06-08 16:07 UTC, jsmitchell approved these changes

2017-06-08 16:32 UTC, nick-drozd approved these changes

2017-06-08 16:38 UTC, merged