Tp
IntelLedger/omi-summer-lab pull request #5
Opened 2017-05-26 17:45 UTC by nick-drozd

2017-05-26 18:44 UTC, peterschwarz requested changes

2017-05-26 18:44 UTC, peterschwarz commented on protos/txn_payload.proto
> +    bytes object = 2;
This should be `payload`or `data`.

2017-05-26 18:44 UTC, peterschwarz commented on omi/sawtooth_omi/handler.py
> +            _validate_object(state_obj, action, signer)
This is less about validating the object, which there should probably be some (minimal, at the moment) validation of the transaction payload, and more about authorizing updates.

I.e. if not `state_obj`, it's an insert, else update.

2017-05-26 19:02 UTC, jsmitchell requested changes

2017-05-26 19:02 UTC, jsmitchell commented on omi/sawtooth_omi/handler.py
> +
Need to do validation of the txn_obj here.

2017-05-26 19:17 UTC, jsmitchell commented on omi/sawtooth_omi/handler.py
> +WORK = 'SetWork'
I would recommend you just use the action name. By taking the verb out, we'll run into trouble if we add alternative actions on the same objects.

2017-05-30 16:55 UTC, nick-drozd commented on omi/sawtooth_omi/handler.py
> +WORK = 'SetWork'
Right now the action doubles as a type tag that gets carried around with the object, so it's convenient to use variables. I'll come up with something cleaner later.

2017-05-30 18:01 UTC, peterschwarz commented on omi/sawtooth_omi/handler.py
> +WORK = 'SetWork'
Doesn't hurt to separate those out.  In fact, if you removed them, you probably don't need constants for the `SetX` actions.

2017-05-30 18:27 UTC, peterschwarz commented on omi/sawtooth_omi/handler.py
> +    txn_obj = transaction.object
This hasn't been updated for the `object` -> `data` change

2017-05-30 19:46 UTC, peterschwarz approved these changes

2017-05-30 20:01 UTC, jsmitchell approved these changes

2017-05-30 20:16 UTC, merged